
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      link: "sqlite::@file(./resource/test.db)"
      table: "user"

  build:
    name: "compat_detect_tool"
    packSrc: "manifest/config,resource/public,resource/template"

  docker:
    build: "-a amd64 -s linux -p temp -ew"
    tagPrefixes:
      - my.image.pub/my-app